# Dockerfile.frontend
FROM node:16

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./


EXPOSE 3000

RUN npm run build

CMD ["npx", "serve", "-s", "build", "-l", "3000"]