FROM python:3.11

WORKDIR /code

COPY . /code/
COPY ./app /code/app
COPY ./src /code/src
COPY ./pyproject.toml /code/pyproject.toml
RUN pip install --no-cache-dir -e . 

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

